### ISSUE TITLE
Replicate results of TF-NAS-A-wose

### ISSUE THREAD

**Issue by soyebn** [AberHu/TF-NAS#3]
Came across very nice work of yours. I am interested in without SE and without hswish configuration.

Following is the search command suggested in readme. Is there any option I can pass to disable these two features from the search? Or do I have to change something in model_search.py?

CUDA_VISIBLE_DEVICES=0 python -u train_search.py \
	--img_root "Your ImageNet Train Set Path" \
	--train_list "./dataset/ImageNet-100-effb0_train_cls_ratio0.8.txt" \
	--val_list "./dataset/ImageNet-100-effb0_val_cls_ratio0.8.txt" \
	--lookup_path "./latency_pkl/latency_gpu.pkl" \
	--target_lat 15.0

**Comment by AberHu** [comment]
There is no option to disable these two features by now. If you want to disable SE, please remove 'MBI_k3_e3_se', 'MBI_k3_e6_se', 'MBI_k5_e3_se', 'MBI_k5_e6_se' of PRIMITIVES and OPS in model_search.py, and change
`self.second_stem = MBInvertedResBlock(32, 32, 8, 16, kernel_size=3, stride=1, affine=True, act_func='relu')`
to
`self.second_stem = MBInvertedResBlock(32, 32, 0, 16, kernel_size=3, stride=1, affine=True, act_func='relu')`
Also, the same modifications must be made in model_eval.py.

If you want to disable hswish, please replace all hswish with relu in model_search.py and model_eval.py. In addition, new latency lookup table needs to be constructed, because the activation is changed. Please refer to [latency_pkl](https://github.com/AberHu/TF-NAS/tree/master/latency_pkl)

**Comment by soyebn** [comment]
Thanks for precise answer. I just started search process after creating new latency table.
One more thing I needed to do was to change config.py. I had to remove last 4 entries in each block for both, mc_mask_dddict and lat_lookup_key_dddict.
